[package]
name = "InvokerFunction"
version = "0.1.0"
authors = ["FabioGentili99 <fabiogentili20@gmail.com>"]
edition = "2021"

[dependencies]
nats= "0.25.0"
quicli= "0.4.0"
tokio = { version = "1.41.1", features = ["full"] }